<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['title'];

    public function films(){
        return $this->hasMany('App\Film');
    }

    public function delete()
    {
        foreach ($this->films as $film){
            $film->delete();
        }
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
